# Dependencies
markdown:         kramdown
highlighter:      pygments

# Gems
plugins:
  - jekyll
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Ana Bittencourt
tagline:          'Design & Development'
description:      'UX Designer and iOS Developer based in Brazil' 
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Ana Bittencourt'
  url:            https://www.linkedin.com/in/anabittencourt

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
